### ISSUE TITLE
Additional Capistrano Tasks

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/mudd-dbs#1]
To run rails, bundler,and passenger tasks through capistrano add the following Gems to the Gemfile:

gem 'capistrano-rails'
gem 'capistrano-bundler'
gem 'capistrano-passenger'

**Comment by sdellis** [comment]
Did this and updated the repo, but I still don't think it worked?  Does it require further customization?

**Comment by kevinreiss** [comment]
Had to make the following two adjuments:

1eb49d9a7647770e7a5c60449624ee68f08f8aa7
d218090231a6396c26505022038d2c8766f90444

Also needed to point the database.yml at the ubuntu location for the mysqld.sock file:

/var/run/mysqld/mysqld.sock 

rather the default /tmp/mysql.sock
