### ISSUE TITLE
Migrate Mudd DB "Search Interfaces" out of Special Collections Drupal Project

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/mudd-dbs#110]
As we prepare to migrate the SC site out of D7 into WDS Site Builder each of the current "Search Interface" content type nodes in D7 need to be migrated into MUDD-DBS so users have a place to begin browsing each collection. 

- [x] Identify which Mudd DBs can be sunset. These are lists that have been compiled in actual finding aids or are no longer needed. These search interfaces can be sunset. Login to the SC site and filter by Content Type = "Search Interface" at https://library.princeton.edu/special-collections/admin/content to see the complete list. 
- [ ] For those lists that are not being sunset identify those that are still being actively updated and ensure Mudd staff are aware of the procedure for doing so. 
- [ ] Create a new roughly equivalent search interface in the Mudd DB application itself for those lists still identified as the primary collection access point. 
- [ ] Put in redirects from the old Drupal based search interface URL to the new one.

**Comment by kevinreiss** [comment]
SC decisions here: https://docs.google.com/spreadsheets/d/1UsMmbMxyJVr03I6NHJ1449_35_OkJW3SNhdaq0nzCaI/edit#gid=1351235624

**Comment by maxkadel** [comment]
Superseded by individual tickets by database.
