### ISSUE TITLE
Create CSV Archives of Collections that will not be migrated

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/mudd-dbs#118]
Each CSV should contain all the field values attached to each model. These can be stored on google sheets. 

- [ ] Confirm with Lynn Durgin/Sara Logue where this should be stored on Drive as Google sheets and ask them who needs access to this data. 

## Collections to archive. 
- [x] Architectural Presentation Boards
- [x] Nassau Literary Magazine Index, 1842-1942
- [x] Princeton Memorabilia Collection
- [x] Princeton University Historical Audio-Visual Collection

## Notes
Content review notes: https://docs.google.com/spreadsheets/d/1UsMmbMxyJVr03I6NHJ1449_35_OkJW3SNhdaq0nzCaI/edit#gid=0. Note these collections are static, not being actively updated.

**Comment by kevinreiss** [comment]
Available here: https://drive.google.com/drive/folders/1Bw5gcKjVa7a39DPRz97x5DvZJyfQRsDT

**Comment by maxkadel** [comment]
Done!
