### ISSUE TITLE
Rails Upgrade to 4.2.2

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/mudd-dbs#12]
@sdellis Do we want to peg this project to specific rails versions or can we just peg it to a general minor version (i.e. 4.2). Immediate question is a recent rails security update.

**Comment by sdellis** [comment]
I don't think there is any reason to peg it to 4.2.2 specifically.  A
general minor version is fine.

**Comment by kevinreiss** [comment]
@sdellis do you think you will have a chance to upgrade this?

**Comment by sdellis** [comment]
Yes.  I will do it right now.
