### ISSUE TITLE
Error occurs on "update" of new_alumni

### ISSUE THREAD

**Issue by sdellis** [pulibrary/mudd-dbs#16]
Update of new_alumni tries to update alumni.

**Comment by sdellis** [comment]
This is related to the fact that the resource name is "new_alumni" and the path helper is getting confused.  @kevinreiss Do you have any suggestions?  Obviously renaming the resource would work, but there are a lot of places it needs to change in the app and then in the url in the RBSC Drupal site.  Do you know if there's an easier way?

**Comment by kevinreiss** [comment]
I'm sorry. I don't quite follow the problem. Could you post any error messages you receive? What are you running to do the update? Is it just a rake db:migrate?

**Comment by sdellis** [comment]
@kevinreiss While most records are loaded via "batch", I've used Devise to allow a couple of staff to log in and update errors/typos in records.  Once logged in, you can see the edit form for "New Alumni" (1921-Present) here:
http://rbsc.princeton.edu/mudd-dbs/new_alumni/215213/edit?

When you click "Update" it takes you here:
http://rbsc.princeton.edu/mudd-dbs/alumni/new.215213

With this error:
>The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.
>

As you can see it seems the name of the resource is likely messing with the rails path helpers.  **My question is do we need to rename the "new_alumni" resource or is there an easier fix?**

FYI - I disabled "sign-up" in Devise so it's not easy to add you as a user.  I could add you as a user via Rails console, but it's not working for me in the dev environment (from current/app/bin). I can demo on Monday via Slack/Hangout if it's still not clear.

**Comment by kevinreiss** [comment]
I was able to pull this application and create a user using this:

```
u = User.new({ email: 'kevin@gmail.com', password: 'testmeagain',password_confirmation: 'testmeagain' })
u.save
```

I experience the same problems you describe. If I switch lines 8 and 9 (https://github.com/pulibrary/mudd-dbs/blob/master/config/routes.rb#L8) so that "new_alumni" is first in the route list those set of forms work as you'd expect but the "alumni" ones have the same problem in reverse. I'm thinking that re-naming the resource is way to go if these need to stay in the same namespace. 

This line is also problematic https://github.com/pulibrary/mudd-dbs/blob/master/app/views/alumni/index.html.erb#L55, There is not a path helper that matches "new_alumn_path". Running ```rake routes``` gives me for the two models in question:

```
mudd-dbs git:(master) ✗ rake routes | grep alumni
                  root GET    /                                      alumni#index
            new_alumni POST   /new_alumni(.:format)                  new_alumni#create
         new_new_alumn GET    /new_alumni/new(.:format)              new_alumni#new
        edit_new_alumn GET    /new_alumni/:id/edit(.:format)         new_alumni#edit
             new_alumn GET    /new_alumni/:id(.:format)              new_alumni#show
                       PATCH  /new_alumni/:id(.:format)              new_alumni#update
                       PUT    /new_alumni/:id(.:format)              new_alumni#update
                       DELETE /new_alumni/:id(.:format)              new_alumni#destroy
                alumni POST   /alumni(.:format)                      alumni#create
                       GET    /alumni/new(.:format)                  alumni#new
            edit_alumn GET    /alumni/:id/edit(.:format)             alumni#edit
                 alumn GET    /alumni/:id(.:format)                  alumni#show
                       PATCH  /alumni/:id(.:format)                  alumni#update
                       PUT    /alumni/:id(.:format)                  alumni#update
                       DELETE /alumni/:id(.:format)                  alumni#destroy
                       GET    /new_alumni(.:format)                  new_alumni#index
                       GET    /alumni(.:format)                      alumni#index
```

**Comment by sdellis** [comment]
Renamed new_alumni resource to recent_alumni.
