### ISSUE TITLE
Set up rake task for scheduled database backups

### ISSUE THREAD

**Issue by sdellis** [pulibrary/mudd-dbs#19]
Rake task should execute a mysql dump of the databases on a schedule.

**Comment by sdellis** [comment]
@kevinreiss Perhaps I should take this last PR #23 a bit further and create one that dumps all the dbs for backup purposes?  If I go ahead with that, is there a preferred place to put these?

**Comment by kevinreiss** [comment]
@sdellis I closed it that one just now. Adding this a rake task to produce this isn't a bad idea. If you do this I would make the task runnable by the Deploy user. I have put them in a directory like /var/www/backups on other application servers.
