### ISSUE TITLE
Remove code that was added for subdirectory

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/mudd-dbs#78]
We should see if this will work for us.  We added some crazy code to make the links work, which we might be able to delete.
https://pulibrary.github.io/2022-03-03-rails-with-subdirectory

Anywhere you see these helpers being utilized should likely be updated if the path business works: https://github.com/pulibrary/mudd-dbs/blob/main/app/helpers/application_helper.rb#L3-L13

**Comment by sandbergja** [comment]
Closing, because we are no longer using this application and using https://github.com/pulibrary/static-tables instead
