### ISSUE TITLE
Department search does not work for several departments

### ISSUE THREAD

**Issue by sdellis** [pulibrary/mudd-dbs#8]
For the Graduate Alumni Database the only problem I found was with the search by department. The search did not populate for the following departments: Art and Archeology, Comparative Lit, Creative Writing, Engineering, Germanic Languages, Medieval Studies, Molecular Bio, Oriental Studies and Special Program in Humanities. I saw names listed as graduates from these departments so I assume it is a problem with the code as opposed to a data entry error. [RM]

**Comment by sdellis** [comment]
Current database has the same issues.  The Department Codes mentioned do not exist in the data set.

**Comment by sandbergja** [comment]
Closing, because we are no longer using this application and using https://github.com/pulibrary/static-tables instead
