### ISSUE TITLE
Upgrade to Ruby 3.1.x

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/mudd-dbs#89]
- [ ]  Add current Ruby 3.1.x to CircleCI
- [ ]  Fix any failing tests or dependency issues caused by upgrade to 3.1.x
- [ ]  Deploy code that hopefully works with both 2.7.5 and 3.1.x
- [ ]  Provision boxes to use Ruby 3.1.x
- [ ]  Remove Ruby 2.7.x from CircleCI

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/mudd-dbs/pull/94
