### ISSUE TITLE
Dead link to Rank and Branches of Service for WWII Memorials

### ISSUE THREAD

**Issue by sdellis** [pulibrary/mudd-dbs#9]
World War II Memorial Book:  The original DB has a line near top that says, "For an explanation of the abbreviations for branches of service included in this database click here and scroll down".  This does NOT appear in the new DB.  The link in the old DB seems dead as well.  [KT]

This is the link from the old site that no longer works:
http://infoshare1.princeton.edu/libraries/firestone/rbsc/finding_aids/rankandbranch.html

**Comment by sdellis** [comment]
Could not locate original file. This is all I could find:
http://infoshare1.princeton.edu/libraries/firestone/rbsc/mudd/online_ex/

**Comment by sandbergja** [comment]
Closing, because we are no longer using this application and using https://github.com/pulibrary/static-tables instead
